# -*- coding: utf-8 -*-
"""RetailPulse360_Chirag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sv1j5AqqoATk9PliwAqzEwMraUkk6HYw

# RETAILPULSE 360
# MainCrafts SkillSprint
# Data Science & Data Analytics Using Python
**Candidate:** Chirag Chhabra  |  **Participant ID:** MT-SKT-1262  |  **Date:** 24 Sep 2026
**Domain:** Data Science & Data Analytics Using Python

## Executive Summary
**What happened?** Company ne 2011–2014 me 51,290 transactions se ₹12.64M sales aur ₹1.47M profit (11.6% margin) banaya. Sales har saal badhi: 2.26M (2011) → 4.30M (2014).

**What matters?** Growth ke saath profit quality barabar nahi badhi. 30% se zyada discount wale orders (10,361 transaction lines) ne kul ₹7.9 lakh se zyada ka loss kiya, jabki bina discount wale orders ne ₹18.3 lakh profit diya. Furniture (margin 6.9%, Tables loss me) aur Southeast Asia (2.0%) / EMEA (5.5%) kamzor hain.

**What should management investigate?** Heavy-discount policy, loss-making products (677 of 3,788), Tables sub-category, aur Turkey/Nigeria/Netherlands jaise loss-making countries.

**What should management consider doing?** Discount ko ~20–30% par cap karna, loss-making products ka pricing/range review, Furniture aur weak regions me margin fix, aur Nov–Dec peak season ke liye inventory plan.

## 01. Business Problem
1. **Problem:** Company ke paas hazaron transactions hain, par pata nahi ki sales aur profit asal me kis wajah se aa rahe hain. (apne words me edit karo)
2. **Why analytics:** Data se pata chalta hai kaun sa product/region/customer paisa bana raha hai aur kahan loss ho raha hai.
3. **Decisions:** Discount policy, product range, region-wise focus, shipping mode, top customers ko retain karna.
4. **KPIs:** Total Sales, Total Profit, Profit Margin, Orders, Customers, Average Order Value, Units Sold.

## 02. Objectives
Understand → Clean → Analyze → Visualize → Discover → Explain → Recommend

## 03. Libraries
- **pandas** – data load, clean, groupby
- **numpy** – calculations
- **matplotlib** – basic charts
- **seaborn** – statistical charts
- **datetime** – date handling
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings; warnings.filterwarnings("ignore")
sns.set_style("whitegrid")
pd.options.display.float_format = '{:,.2f}'.format
print("Libraries loaded successfully.")

"""## 04. Data Loading
Colab me left sidebar → Files → dataset upload karo, phir file ka naam neeche change karo.
"""

FILE = "superstore.csv"   # <-- apni file ka naam yahan likho
try:
    df = pd.read_csv(FILE, encoding="utf-8")
except Exception:
    df = pd.read_excel(FILE)
# Column names ko standard karna (Global Superstore me kabhi underscore/hyphen alag hote hain)
df.columns = [c.strip().replace(".", " ") for c in df.columns]   # Customer.ID -> Customer ID
df = df.rename(columns={"Order_Date":"Order Date","Ship_Date":"Ship Date","Customer_ID":"Customer ID","Customer_Name":"Customer Name",
    "Order_ID":"Order ID","Ship_Mode":"Ship Mode","Sub_Category":"Sub-Category","Product_Name":"Product Name","Sub Category":"Sub-Category",
    "Order Priority":"Order Priority"})
print("Dataset loaded successfully.")
print("Rows:", df.shape[0]); print("Columns:", df.shape[1])
display(df.head())

"""## 05. Data Understanding"""

df.info()
display(df.describe(include="all").T)
display(df.head(10))

print("Numerical:", df.select_dtypes(include="number").columns.tolist())
print("Categorical:", df.select_dtypes(include="object").columns.tolist())

"""### Data Dictionary
| Column | Meaning | Type |
|---|---|---|
| Order ID | Unique order number | Identifier |
| Order Date | Order placed date | Date |
| Ship Date | Order shipped date | Date |
| Ship Mode | Shipping method | Categorical |
| Customer ID / Name | Customer identity | Identifier |
| Segment | Consumer / Corporate / Home Office | Categorical |
| Country / Region | Location | Categorical |
| Category / Sub-Category | Product group | Categorical |
| Product Name | Product | Categorical |
| Sales | Revenue | Numeric |
| Quantity | Units ordered | Numeric |
| Discount | Discount applied | Numeric |
| Profit | Profit / loss | Numeric |

## 06. Data Quality Check
"""

missing = df.isnull().sum()
print("Missing values:"); display(missing[missing>0])
dups = df.duplicated().sum()
print("Duplicate rows:", dups)
print(df.dtypes)
for c in df.select_dtypes(include="object").columns:
    print(c, "->", df[c].nunique(), "unique")
print(f'''
DATA QUALITY SUMMARY
Total records : {df.shape[0]}
Total columns : {df.shape[1]}
Missing values: {int(missing.sum())}
Duplicates    : {dups}
Date fields   : Order Date, Ship Date (object -> datetime me convert karenge)
''')

"""## 07. Data Cleaning"""

df["Order Date"] = pd.to_datetime(df["Order Date"], errors="coerce", dayfirst=False)
df["Ship Date"]  = pd.to_datetime(df["Ship Date"],  errors="coerce", dayfirst=False)
print(df["Order Date"].dtype, "| Null dates:", df["Order Date"].isnull().sum(), df["Ship Date"].isnull().sum())
before = len(df)
df["Discount"] = df["Discount"].round(2)   # float precision fix (0.2 vs 0.2000001)
df = df.drop_duplicates()   # Reason: exact duplicate rows same transaction ko double count karte hain
print("Rows removed:", before-len(df))

"""**Cleaning notes:** Dates ko datetime me convert kiya taaki time analysis ho sake. Duplicate rows sirf tab hataye jab exact same the (double counting rokne ke liye). Koi column delete nahi kiya.

## 08. Feature Engineering
"""

df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month
df["Month_Name"] = df["Order Date"].dt.month_name()
df["Order_Month"] = df["Order Date"].dt.to_period("M").astype(str)
df["Shipping_Days"] = (df["Ship Date"] - df["Order Date"]).dt.days
df["Profit_Margin"] = np.where(df["Sales"]!=0, df["Profit"]/df["Sales"]*100, 0)  # zero-sales safe
display(df[["Order Date","Year","Month_Name","Order_Month","Shipping_Days","Profit_Margin"]].head())

"""## 09. KPI Analysis"""

total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
total_orders = df["Order ID"].nunique()
total_customers = df["Customer ID"].nunique()
total_quantity = df["Quantity"].sum()
average_order_value = total_sales/total_orders
profit_margin = total_profit/total_sales*100
print("="*40); print("RETAILPULSE 360 — BUSINESS KPIs"); print("="*40)
print(f"Total Sales        : {total_sales:,.2f}")
print(f"Total Profit       : {total_profit:,.2f}")
print(f"Total Orders       : {total_orders:,}")
print(f"Total Customers    : {total_customers:,}")
print(f"Units Sold         : {total_quantity:,}")
print(f"Average Order Value: {average_order_value:,.2f}")
print(f"Profit Margin      : {profit_margin:.2f}%"); print("="*40)

"""## 10. Sales Analysis (Category)"""

category_sales = df.groupby("Category")["Sales"].sum().sort_values(ascending=False)
display(category_sales)
category_sales.plot(kind="bar", figsize=(8,5), color=sns.color_palette("viridis",len(category_sales)))
plt.title("Sales by Category"); plt.xlabel("Category"); plt.ylabel("Sales"); plt.xticks(rotation=0); plt.show()
print(f"Highest-sales category: {category_sales.index[0]} ({category_sales.iloc[0]:,.0f})")
print(f"Lowest-sales category : {category_sales.index[-1]} ({category_sales.iloc[-1]:,.0f})")
subcat = df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False)
subcat.plot(kind="barh", figsize=(8,7)); plt.title("Sales by Sub-Category"); plt.gca().invert_yaxis(); plt.show()

"""**Interpretation:** The highest-sales category is **Technology** with **₹4.74M** sales (37.5% of total). The lowest is **Office Supplies** with ₹3.79M. Teeno categories ke sales kaafi close hain (Furniture 4.11M), yaani revenue kisi ek category par depend nahi karta.

## 11. Regional Analysis
"""

region_sales = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)
profit_region = df.groupby("Region")["Profit"].sum().sort_values(ascending=False)
display(pd.DataFrame({"Sales":region_sales,"Profit":profit_region}).assign(Margin_pct=lambda x:x.Profit/x.Sales*100))
fig,ax=plt.subplots(1,2,figsize=(14,5))
region_sales.plot(kind="bar",ax=ax[0],title="Sales by Region"); profit_region.plot(kind="bar",ax=ax[1],color="green",title="Profit by Region")
plt.show()
print(f"Top region {region_sales.index[0]} = {region_sales.iloc[0]/region_sales.sum()*100:.1f}% of total sales")
print("Lowest sales region:", region_sales.index[-1])
print("Lowest profit region:", profit_region.index[-1])

"""**Answers:** Sabse zyada sales **Central (₹2.82M, 22.3%)**, sabse kam **Canada (₹0.07M)**. Lekin high sales = high profit nahi hai: **South** ka sales 1.60M (2nd) hai par margin sirf 8.8%; **Southeast Asia** ka sales 0.88M hai par margin 2.0%; jabki **Canada** ka margin 26.6% (sabse zyada) hai. Yaani sales rank aur profit rank alag hain.

## 12. Profitability Analysis
"""

category_profit = df.groupby("Category")["Profit"].sum().sort_values(ascending=False)
display(category_profit)
cat = pd.DataFrame({"Sales":category_sales,"Profit":category_profit}); cat["Margin_%"]=cat.Profit/cat.Sales*100
display(cat)
print("Highest sales:", category_sales.index[0], "| Highest profit:", category_profit.index[0])
subp = df.groupby("Sub-Category")["Profit"].sum().sort_values()
subp.plot(kind="barh", figsize=(8,7), color=["red" if v<0 else "green" for v in subp]); plt.title("Profit by Sub-Category"); plt.show()

"""## 13. Product Analysis — Loss-making Products"""

product_profit = df.groupby("Product Name")["Profit"].sum().sort_values()
loss_products = product_profit[product_profit<0]
print("Loss-making products:", len(loss_products), "of", len(product_profit))
top10 = loss_products.head(10).index
detail = (df[df["Product Name"].isin(top10)].groupby("Product Name")
    .agg(Sales=("Sales","sum"),Profit=("Profit","sum"),Avg_Discount=("Discount","mean"),Quantity=("Quantity","sum"),
         Category=("Category","first"),Top_Region=("Region",lambda x:x.mode()[0])).sort_values("Profit"))
display(detail)
print("Top 10 most profitable products:"); display(product_profit.tail(10)[::-1])

"""**Interpretation:** 3,788 me se **677 products loss me** hain. Top-10 loss products (3D printers, Bevis tables, Lexmark printer, Motorola phone) ka kul loss ≈ **₹40,050** hai jabki inki sales ₹1.44 lakh hai. Inpe average discount **24.2%** hai, jo company average (14.3%) se kaafi zyada hai. Tables sub-category poori tarah loss me hai (−₹64,083). Data yeh dikhata hai ki loss ka ek bada hissa high discount se juda hai (par yeh sirf association hai).

## 14. Discount vs Profit
"""

plt.figure(figsize=(9,6))
sns.scatterplot(data=df,x="Discount",y="Profit",alpha=0.4)
plt.title("Relationship Between Discount and Profit"); plt.show()
discount_profit = df.groupby("Discount")["Profit"].mean().sort_index()
display(discount_profit)
discount_profit.plot(kind="bar",figsize=(10,5),color=["red" if v<0 else "green" for v in discount_profit]); plt.title("Average Profit by Discount"); plt.show()
print("Correlation (Discount, Profit):", round(df["Discount"].corr(df["Profit"]),3))

"""**Answer:** Haan — higher discount ke saath average profit girta hai (correlation **−0.32**). 0% discount par avg profit ≈ ₹62 per line; 0–20% par ₹43; 20–30% par −₹22; 30–50% par −₹62; 50%+ par −₹99. Discount 30% ke upar jaate hi orders average loss me jaate hain.
**Caution:** Yeh *association* hai, *causation* nahi — product mix, category aur region jaise doosre factors bhi asar dalte hain, aur discount kis wajah se diya gaya yeh data me nahi hai.

## 15. Time-Series Analysis
"""

monthly_sales = df.groupby("Order_Month")["Sales"].sum()
monthly_sales.plot(figsize=(12,5)); plt.title("Monthly Sales Trend"); plt.xlabel("Month"); plt.ylabel("Sales"); plt.xticks(rotation=45); plt.show()
yearly_sales = df.groupby("Year")["Sales"].sum(); display(yearly_sales)
display(yearly_sales.pct_change().mul(100).rename("YoY_growth_%"))
print("Highest month:", monthly_sales.idxmax(), f"{monthly_sales.max():,.0f}")
print("Lowest month :", monthly_sales.idxmin(), f"{monthly_sales.min():,.0f}")
seasonal = df.groupby("Month_Name")["Sales"].sum().reindex(pd.date_range("2000-01-01",periods=12,freq="MS").month_name())
seasonal.plot(kind="bar",figsize=(10,4),title="Seasonality: Sales by Calendar Month"); plt.show()

"""## 16. Customer Analysis"""

customer_sales = df.groupby(["Customer ID","Customer Name"])["Sales"].sum().sort_values(ascending=False)
customer_profit = df.groupby(["Customer ID","Customer Name"])["Profit"].sum().sort_values(ascending=False)
print("Top 10 by Sales"); display(customer_sales.head(10))
print("Top 10 by Profit"); display(customer_profit.head(10))
overlap = set(customer_sales.head(10).index) & set(customer_profit.head(10).index)
print("Common in both top-10 lists:", len(overlap))
print(f"Sales per customer (avg): {customer_sales.mean():,.2f}")
print(f"Top 10% customers contribute {customer_sales.head(int(len(customer_sales)*0.1)).sum()/customer_sales.sum()*100:.1f}% of sales")
print("Loss-making customers:", (customer_profit<0).sum())

"""## 17. Segment Analysis"""

segment_analysis = df.groupby("Segment").agg(Sales=("Sales","sum"),Profit=("Profit","sum"),
    Customers=("Customer ID","nunique"),Orders=("Order ID","nunique"))
segment_analysis["Profit_Margin"]=segment_analysis.Profit/segment_analysis.Sales*100
display(segment_analysis)
segment_analysis[["Sales","Profit"]].plot(kind="bar",figsize=(8,5),title="Segment: Sales vs Profit"); plt.xticks(rotation=0); plt.show()
print("Highest sales:",segment_analysis.Sales.idxmax()); print("Highest profit:",segment_analysis.Profit.idxmax())
print("Highest margin:",segment_analysis.Profit_Margin.idxmax()); print("Largest customer base:",segment_analysis.Customers.idxmax())

"""## 18. Shipping Analysis"""

avg_shipping = df.groupby("Ship Mode")["Shipping_Days"].mean().sort_values(); display(avg_shipping)
ship = df.groupby("Ship Mode").agg(Orders=("Order ID","nunique"),Avg_Days=("Shipping_Days","mean"),Profit=("Profit","sum"),Sales=("Sales","sum"))
ship["Margin_%"]=ship.Profit/ship.Sales*100; display(ship)
print("Avg delivery time (all):", round(df["Shipping_Days"].mean(),2), "days")
display(df.groupby("Region")["Shipping_Days"].mean().sort_values(ascending=False))
if "Order Priority" in df.columns:
    display(df.groupby("Order Priority").agg(Orders=("Order ID","nunique"),Avg_Days=("Shipping_Days","mean"),Profit=("Profit","sum")))
ship["Orders"].plot(kind="pie",autopct="%1.1f%%",figsize=(5,5),title="Shipping Mode Usage"); plt.ylabel(""); plt.show()

"""**Answer:** Nahi. Margin sab shipping modes me lagbhag same hai (Same Day 11.4%, First Class 11.4%, Second Class 11.4%, Standard 11.8%). Standard Class sabse zyada use hoti hai (15,154 orders) aur sabse zyada profit deti hai (₹8.9 lakh). Average delivery 3.97 din.

## 19. Top 10 Insights
| # | Finding | Evidence | Business Meaning |
|---|---|---|---|
| 1 | Sales har saal grow hui | 2.26M (2011) → 4.30M (2014); YoY +18.5%, +27.2%, +26.3% | Business expand kar raha hai; growth sustain karne ke liye planning chahiye |
| 2 | Technology sabse bada category hai | 4.74M sales, 663.8K profit (14.0% margin) | Sabse bada revenue aur profit source |
| 3 | Furniture ka margin kamzor hai | 4.11M sales par margin sirf 6.9%; Tables = −64K profit | Sales achhi par profit kam — pricing/discount review zaroori |
| 4 | Discount 30% ke upar loss karata hai | Corr −0.32; 30–50% par avg −₹62, 50%+ par −₹99 per line | Heavy discounts profit destroy karte hain |
| 5 | Central sabse bada region | 2.82M sales (22.3%), profit 311K | Core market — protect karna chahiye |
| 6 | High sales ≠ high profit | Southeast Asia margin 2.0%, EMEA 5.5%, South 8.8% vs Canada 26.6% | Region strategy sales ke saath margin dekh ke banani chahiye |
| 7 | 677 products loss me hain | Top 10 loss products ka loss ≈ ₹40K, avg discount 24.2% | Pricing/discount ya range review |
| 8 | Loss-making customers | 1,058 of 4,873 customers negative profit; total ≈ −₹3.75 lakh | Customer profitability alag se track karo |
| 9 | Peak season Q4 | Highest month Nov-2014 (555K); Dec aur Nov top calendar months | Inventory aur staffing Nov–Dec ke liye plan karo |
| 10 | Shipping mode profit ko affect nahi karta | Margin ~11.4–11.8% sab modes me; Standard = 15,154 orders | Faster shipping se profit nahi badhta; cost-efficient mode use karo |

## 20. Business Question Table
| Business Question | Finding | Evidence | Action |
|---|---|---|---|
| Which category sells most? | Technology | 4.74M sales | Stock aur marketing me priority |
| Which category is most profitable? | Technology (Furniture kamzor) | Profit 663.8K; Furniture margin 6.9% | Furniture pricing/discount fix |
| Which region needs attention? | Southeast Asia, EMEA, South | Margins 2.0%, 5.5%, 8.8% | Discount aur cost review |
| Does discount affect profit? | Haan, negative association | Corr −0.32; 30%+ discount = loss | Discount cap |
| Who are the top customers? | Sean Miller (sales), Tamara Chand (profit + #2 sales) | 25,042 sales; 8,981 profit | Retention/loyalty program |

## 21. Mini Analytics Dashboard
"""

fig = plt.figure(figsize=(18,14))
gs = fig.add_gridspec(4,4)
kpis=[("Total Sales",f"{total_sales:,.0f}"),("Total Profit",f"{total_profit:,.0f}"),("Total Orders",f"{total_orders:,}"),("Profit Margin",f"{profit_margin:.1f}%")]
for i,(k,v) in enumerate(kpis):
    a=fig.add_subplot(gs[0,i]); a.axis("off"); a.text(0.5,0.6,v,ha="center",fontsize=24,weight="bold",color="#1f4e79"); a.text(0.5,0.2,k,ha="center",fontsize=13)
    a.add_patch(plt.Rectangle((0,0),1,1,fill=False,ec="#1f4e79",lw=2,transform=a.transAxes))
a=fig.add_subplot(gs[1,:2]); monthly_sales.plot(ax=a); a.set_title("Sales Trend"); a.tick_params(axis="x",rotation=45)
a=fig.add_subplot(gs[1,2:]); category_sales.plot(kind="bar",ax=a,color="teal"); a.set_title("Sales by Category"); a.tick_params(axis="x",rotation=0)
a=fig.add_subplot(gs[2,:2]); profit_region.plot(kind="bar",ax=a,color=["red" if v<0 else "green" for v in profit_region]); a.set_title("Profit by Region")
a=fig.add_subplot(gs[2,2:]); segment_analysis[["Sales","Profit"]].plot(kind="bar",ax=a); a.set_title("Customer Segments"); a.tick_params(axis="x",rotation=0)
a=fig.add_subplot(gs[3,:]); sns.scatterplot(data=df,x="Discount",y="Profit",alpha=0.3,ax=a); a.set_title("Discount vs Profit")
fig.suptitle("RETAILPULSE 360 — Analytics Dashboard",fontsize=20,weight="bold"); plt.tight_layout(); plt.savefig("dashboard.png",dpi=150); plt.show()

"""## 22. Final Recommendations
**Recommendation 1 — Discount cap**
- Observation: 30%+ discount par orders loss me jaate hain.
- Evidence: Avg profit 30–50% par −₹62, 50%+ par −₹99 per line; correlation −0.32.
- Recommended Action: Discount ko 20–30% tak cap karo; usse zyada ke liye manager approval.
- Expected Business Purpose: Loss kam karke margin 11.6% se upar le jana.

**Recommendation 2 — Furniture / Tables review**
- Observation: Furniture ka margin sabse kam hai aur Tables loss me hai.
- Evidence: Margin 6.9%; Tables profit −₹64,083.
- Recommended Action: Tables ki pricing badhao ya supplier cost/discount review karo.
- Expected Business Purpose: Furniture ko profitable banana.

**Recommendation 3 — Loss-making products**
- Observation: 677 products loss me hain.
- Evidence: Top-10 loss products (Cubify 3D printers, Bevis tables) ka loss ≈ ₹40K, avg discount 24.2%.
- Recommended Action: In products ki discount band karo, price revise karo ya range se hatao.
- Expected Business Purpose: Avoidable loss rokna.

**Recommendation 4 — Weak regions**
- Observation: Kuch regions me sales achhi par margin bahut kam.
- Evidence: Southeast Asia 2.0%, EMEA 5.5%, South 8.8%; Turkey aur Nigeria sabse zyada loss wale countries.
- Recommended Action: In markets me discount aur shipping/cost structure review karo.
- Expected Business Purpose: Sales ko profit me convert karna.

**Recommendation 5 — Peak season & top customers**
- Observation: Nov–Dec peak hain; top 10% customers 31.3% sales dete hain.
- Evidence: Nov-2014 = 555K (highest month); top-10% customer share 31.3%.
- Recommended Action: Q4 ke liye inventory pehle se plan karo aur high-value customers ke liye loyalty offers do.
- Expected Business Purpose: Peak revenue capture aur retention.

## 23. Limitations
1. Dataset historical hai — future market conditions alag ho sakti hain.
2. Analysis correlation dikhata hai, causation prove nahi karta (discount vs profit).
3. Marketing spend, competitor, customer satisfaction, returns jaisa external data available nahi hai.

## 24. Final Conclusion
RetailPulse 360 dikhata hai ki business tezi se grow kar raha hai (2011–2014 me sales ~1.9x), par growth aur profit barabar nahi hain. Asli problem heavy discounting, kuch loss-making products/Furniture-Tables, aur low-margin regions hain. In par action lene se profit margin (abhi 11.6%) improve ho sakta hai bina sales kam kiye.

## 25. Optional: RFM Customer Segmentation
"""

snap = df["Order Date"].max()+pd.Timedelta(days=1)
rfm = df.groupby("Customer ID").agg(Recency=("Order Date",lambda x:(snap-x.max()).days),Frequency=("Order ID","nunique"),Monetary=("Sales","sum"))
rfm["R"]=pd.qcut(rfm.Recency,4,labels=[4,3,2,1]).astype(int); rfm["F"]=pd.qcut(rfm.Frequency.rank(method="first"),4,labels=[1,2,3,4]).astype(int); rfm["M"]=pd.qcut(rfm.Monetary,4,labels=[1,2,3,4]).astype(int)
rfm["Score"]=rfm.R+rfm.F+rfm.M
rfm["Group"]=pd.cut(rfm.Score,[0,5,8,12],labels=["Low value","Mid value","High value"])
display(rfm.Group.value_counts()); display(rfm.groupby("Group")[["Recency","Frequency","Monetary"]].mean())